// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHGECiO2K21Z94gAU4GLWs-NWIEAYkgK8',
    appId: '1:290254642130:android:7f45a08fb85de823ad060b',
    messagingSenderId: '290254642130',
    projectId: 'selahapp-1',
    storageBucket: 'selahapp-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8mqTEdaBxNoHVLmEdt7VhMnwBteR_TPk',
    appId: '1:290254642130:ios:3d380640934a4958ad060b',
    messagingSenderId: '290254642130',
    projectId: 'selahapp-1',
    storageBucket: 'selahapp-1.firebasestorage.app',
    androidClientId: '290254642130-o2k8k4acn3ekdec0me73b1ftbqt2u46t.apps.googleusercontent.com',
    iosClientId: '290254642130-fg8rtbi81ro0079bttflp32ftrct3qs4.apps.googleusercontent.com',
    iosBundleId: 'in.selahapp.app',
  );
}
