-- =============================================================================
-- Bible Database Schema (SQLite with FTS5)
-- =============================================================================
--
-- This schema defines the read-only Bible database used by the Notify app.
-- It is a SEPARATE SQLite file from the app's sync database (selah-prod_sync.db).
--
-- File: assets/bible.db
-- Generated by: tools/generate_bible_db.dart
-- Schema version: 1
--
-- Design decisions:
--   - Separate DB file prevents any interaction with sync, global search,
--     or songs search infrastructure.
--   - FTS5 uses content-sync mode (content='bible_verses', content_rowid='id')
--     so the FTS index is automatically maintained via triggers.
--   - The _meta table stores the schema version for migration support.
--     When the bundled DB version exceeds the installed version, the app
--     replaces the file from assets.
--   - The database is conceptually read-only from the app's perspective.
--     BibleRepository exposes no write operations.
-- =============================================================================

-- Version tracking for migration support
CREATE TABLE _meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
INSERT INTO _meta (key, value) VALUES ('schema_version', '1');

-- =============================================================================
-- Table: bible_books
-- =============================================================================
-- One row per canonical book (66 total).
-- id uses the standard canonical numbering (1 = Genesis, 66 = Revelation).
-- testament: 0 = Old Testament, 1 = New Testament.
-- sort_order matches id for canonical ordering.

CREATE TABLE bible_books (
  id INTEGER PRIMARY KEY,           -- 1..66 (canonical numbering)
  name TEXT NOT NULL,                -- e.g., "John", "1 Corinthians"
  short_name TEXT NOT NULL,          -- e.g., "John", "1Cor"
  testament INTEGER NOT NULL,        -- 0 = OT, 1 = NT
  sort_order INTEGER NOT NULL        -- 1..66 (canonical order)
);

-- Index for filtering by testament and ordering
CREATE INDEX idx_books_testament ON bible_books(testament, sort_order);

-- =============================================================================
-- Table: bible_verses
-- =============================================================================
-- One row per (translation, book, chapter, verse) tuple.
-- ~31,000 rows for KJV. Additional translations add more rows.
-- UNIQUE constraint prevents duplicate verse entries.

CREATE TABLE bible_verses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  translation TEXT NOT NULL,         -- e.g., "KJV", "ESV"
  book_id INTEGER NOT NULL           -- FK → bible_books.id
    REFERENCES bible_books(id),
  chapter INTEGER NOT NULL,          -- 1-indexed chapter number
  verse INTEGER NOT NULL,            -- 1-indexed verse number
  text TEXT NOT NULL,                -- Full verse text
  UNIQUE(translation, book_id, chapter, verse)
);

-- Composite index for fast coordinate-based lookup
-- Covers the primary access pattern: lookup by (book, chapter, verse)
CREATE INDEX idx_verse_lookup ON bible_verses(book_id, chapter, verse);

-- =============================================================================
-- Virtual Table: bible_verses_fts (FTS5)
-- =============================================================================
-- Full-text search index on verse text.
-- Uses external content mode: the FTS table does not store its own copy of
-- the text. Instead, it references bible_verses via content_rowid.
-- This halves storage compared to a standalone FTS table.
--
-- Triggers below keep the FTS index in sync with bible_verses.

CREATE VIRTUAL TABLE bible_verses_fts USING fts5(
  text,
  content='bible_verses',
  content_rowid='id'
);

-- =============================================================================
-- Triggers: FTS sync
-- =============================================================================
-- These triggers maintain the FTS5 index whenever bible_verses changes.
-- In practice the data is read-only after generation, but triggers ensure
-- correctness if translations are ever added at runtime.

-- AFTER INSERT: index the new verse text
CREATE TRIGGER bible_verses_ai AFTER INSERT ON bible_verses BEGIN
  INSERT INTO bible_verses_fts(rowid, text) VALUES (new.id, new.text);
END;

-- AFTER DELETE: remove the deleted verse from the FTS index
CREATE TRIGGER bible_verses_ad AFTER DELETE ON bible_verses BEGIN
  INSERT INTO bible_verses_fts(bible_verses_fts, rowid, text)
    VALUES ('delete', old.id, old.text);
END;

-- AFTER UPDATE: re-index the changed verse
CREATE TRIGGER bible_verses_au AFTER UPDATE ON bible_verses BEGIN
  INSERT INTO bible_verses_fts(bible_verses_fts, rowid, text)
    VALUES ('delete', old.id, old.text);
  INSERT INTO bible_verses_fts(rowid, text) VALUES (new.id, new.text);
END;

-- =============================================================================
-- Example Queries
-- =============================================================================

-- 1. Book selector: all books ordered by canonical position
--    SELECT * FROM bible_books ORDER BY sort_order;

-- 2. Book selector: Old Testament only
--    SELECT * FROM bible_books WHERE testament = 0 ORDER BY sort_order;

-- 3. Chapter selector: distinct chapters for John (id=43) in KJV
--    SELECT DISTINCT chapter FROM bible_verses
--    WHERE book_id = 43 AND translation = 'KJV'
--    ORDER BY chapter;

-- 4. Verse selector: all verses in John chapter 3 (KJV)
--    SELECT * FROM bible_verses
--    WHERE book_id = 43 AND chapter = 3 AND translation = 'KJV'
--    ORDER BY verse;

-- 5. Single verse lookup: John 3:16 (KJV)
--    SELECT * FROM bible_verses
--    WHERE book_id = 43 AND chapter = 3 AND verse = 16 AND translation = 'KJV';

-- 6. Verse range: John 3:16-18 (KJV)
--    SELECT * FROM bible_verses
--    WHERE book_id = 43 AND chapter = 3 AND verse >= 16 AND verse <= 18
--          AND translation = 'KJV'
--    ORDER BY verse;

-- 7. FTS5 full-text search: find "God so loved" in KJV
--    SELECT bv.* FROM bible_verses bv
--    JOIN bible_verses_fts fts ON bv.id = fts.rowid
--    WHERE fts.text MATCH '"God so loved"'
--      AND bv.translation = 'KJV'
--    ORDER BY bv.book_id, bv.chapter, bv.verse
--    LIMIT 50;

-- 8. FTS5 prefix search: find verses starting with "lov" in KJV
--    SELECT bv.* FROM bible_verses bv
--    JOIN bible_verses_fts fts ON bv.id = fts.rowid
--    WHERE fts.text MATCH 'lov*'
--      AND bv.translation = 'KJV'
--    LIMIT 50;

-- 9. Available translations
--    SELECT DISTINCT translation FROM bible_verses ORDER BY translation;

-- 10. Verse count per book (for a translation)
--     SELECT bb.name, COUNT(*) as verse_count
--     FROM bible_verses bv
--     JOIN bible_books bb ON bv.book_id = bb.id
--     WHERE bv.translation = 'KJV'
--     GROUP BY bv.book_id
--     ORDER BY bb.sort_order;
